### ISSUE TITLE
Matplotlib error

### ISSUE THREAD

**Issue by AlexTaverna** [seanmcleod/EMDiagrams#1]
i was trying to run EMDiagrmas.py and i get this error at line 250

```
Traceback (most recent call last):
  File "c:\Users\macch\Desktop\EMDiagrams-master\EMDiagrams.py", line 250, in <module>
    render(aircraft, altitude, weight, g_values, radius_values, ps_values, legend)
  File "c:\Users\macch\Desktop\EMDiagrams-master\EMDiagrams.py", line 221, in render
    render_background(ax, altitude, g_values, radius_values)
  File "c:\Users\macch\Desktop\EMDiagrams-master\EMDiagrams.py", line 103, in render_background
    ax.grid(b=True, which='minor', color='0.85', linestyle='--')
  File "C:\Users\macch\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\axes\_base.py", line 3194, in grid
    self.xaxis.grid(visible, which=which, **kwargs)
  File "C:\Users\macch\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\axis.py", line 1656, in grid
    self.set_tick_params(which='minor', **gridkw)
  File "C:\Users\macch\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\axis.py", line 932, in set_tick_params
    kwtrans = self._translate_tick_params(kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\macch\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\axis.py", line 1076, in _translate_tick_params
    raise ValueError(
ValueError: keyword grid_b is not recognized; valid keywords are ['size', 'width', 'color', 'tickdir', 'pad', 'labelsize', 'labelcolor', 'zorder', 'gridOn', 'tick1On', 'tick2On', 'label1On', 'label2On', 'length', 'direction', 'left', 'bottom', 'right', 'top', 'labelleft', 'labelbottom', 'labelright', 'labeltop', 'labelrotation', 'grid_agg_filter', 'grid_alpha', 'grid_animated', 'grid_antialiased', 'grid_clip_box', 'grid_clip_on', 'grid_clip_path', 'grid_color', 'grid_dash_capstyle', 'grid_dash_joinstyle', 'grid_dashes', 'grid_data', 'grid_drawstyle', 'grid_figure', 'grid_fillstyle', 'grid_gapcolor', 'grid_gid', 'grid_in_layout', 'grid_label', 'grid_linestyle', 'grid_linewidth', 'grid_marker', 'grid_markeredgecolor', 'grid_markeredgewidth', 'grid_markerfacecolor', 'grid_markerfacecoloralt', 'grid_markersize', 'grid_markevery', 'grid_mouseover', 'grid_path_effects', 'grid_picker', 'grid_pickradius', 'grid_rasterized', 'grid_sketch_params', 'grid_snap', 'grid_solid_capstyle', 'grid_solid_joinstyle', 'grid_transform', 'grid_url', 'grid_visible', 'grid_xdata', 'grid_ydata', 'grid_zorder', 'grid_aa', 'grid_c', 'grid_ds', 'grid_ls', 'grid_lw', 'grid_mec', 'grid_mew', 'grid_mfc', 'grid_mfcalt', 'grid_ms']
```

**Comment by seanmcleod** [comment]
Looks like the error is coming from line 103.

https://github.com/seanmcleod/EMDiagrams/blob/88f18f3932735502e3bd2b2a616b773e43846189/EMDiagrams.py#L103

Worked fine at the time I wrote the original code 2 years ago. I see you're more than likely running a much newer version of matplotlib given the references to Python 3.11.

Just tried running it on my PC now, I'm currently running Python 3.9 and matplotlib 3.5.1, and I get the graph generated fine, however I also get the following deprecation warning.

```sh
C:\source\EMDiagrams\EMDiagrams.py:103: MatplotlibDeprecationWarning: The 'b' parameter of grid() has been renamed 'visible' since Matplotlib 3.5; support for the old name will be dropped two minor releases later.
  ax.grid(b=True, which='minor', color='0.85', linestyle='--')
C:\source\EMDiagrams\EMDiagrams.py:104: MatplotlibDeprecationWarning: The 'b' parameter of grid() has been renamed 'visible' since Matplotlib 3.5; support for the old name will be dropped two minor releases later.
  ax.grid(b=True, which='major', color='0.65', linestyle='-')
```

So I've just pushed a commit to change `b=True` to `visible=True` - https://github.com/seanmcleod/EMDiagrams/commit/c9ec7d75acca701922d358d4a391172e5d251509 to fix this issue.

Out of interest how are you planning on using the EMDiagram code?

**Comment by AlexTaverna** [comment]
i can confirm now it works!

there is one thing that i don't understand, what is the meaning of the variables used to describre the aircraft:
- self.CLMax 
- self.S 
- self.Maxg (maximum amounnt of Gs the aircraft can take)
- self.Vne 
- self.DragIndex (additional drag innduced by external objects attached to the plane like bombs, missiles, droptanks, ecc..  )
- self.k 

I'm planning to use the EMDiagrams for a project realted to table top games

**Comment by seanmcleod** [comment]
- **CLMax** - maximum coefficient of lift, i.e. at the start of the stall
- **S** - wing area
- **Maxg** - maximum g an aircraft is rated for structurally
- **Vne** - Velocity never exceed, i.e. max velocity
- **DragIndex** - used to calculate how much extra drag there is based on external stores loaded
- **k** - factor used to describe the efficiency of the wing

If you haven't already, also take a look at the Jupyter notebook in the repo, can view it directly on Github - https://github.com/seanmcleod/EMDiagrams/blob/master/EMDiagrams.ipynb

> I'm planning to use the EMDiagrams for a project realted to table top games

Based on this repo - https://github.com/AlexTaverna/arcade-game-ursina?

**Comment by AlexTaverna** [comment]
thanks for the answer! 

> Based on this repo - https://github.com/AlexTaverna/arcade-game-ursina?
no, is a compile different project
